from time import sleep

print('Olá, você me executou com sucesso...')
sleep(2)
print('Aguardou 2 segundos')
sleep(2)
print('Aguardou 2 segundos')
sleep(2)
print('Aguardou 2 segundos')
sleep(2)
print('Aguardou 2 segundos')
sleep(2)
print('Aguardou 2 segundos')
sleep(2)
print('Aguardou 2 segundos')
sleep(2)
print('Aguardou 2 segundos')
sleep(2)
print('Aguardou 2 segundos')
sleep(2)
print('Aguardou 2 segundos')
